clean:
	- rm *.png

snowman:
	java Main.java -image snowman.png -size 1000 -threshold 5000 -xlo -1.236 -xhi -1.191 -ylo 0.14 -yhi 0.172

fields:
	java Main.java -image snowman.png -size 1000 -threshold 5000 -xlo -0.749988 -xhi -1.191 -ylo 0.14 -yhi 0.172

dragon:
	java Main.java -image snowman.png -size 1000 -threshold 5000 -xlo -1.236 -xhi -1.191 -ylo 0.14 -yhi 0.172
